### PR TITLE
Japanese issue templates translation

### PR DESCRIPTION
**Pull request by Ryuuen**
Translated into Japanese from Description.
I am not quite sure about the table above, so I just made a little correction. If the correction is wrong, please tell me.

### CODE REVIEW

**Comment by Tibowl** [comment]
"Combat bug" in table can also be translated, as well as the description. They're shown [when selecting a template](https://github.com/Tibowl/KCBugTracker/issues/new/choose).
image

The other templates are fairly. 
The different versions should be in different files, but I can fix that myself in case you're having trouble with using GitHub.

**Comment by Ryuuen** [comment]
OK. It helps a lot if you can fix it by yourself.
And I noticed that the translated contents in different templates are the same. Maybe it is convient for you to just to copy out the contents to create other Japanese templates.

**Comment by Tibowl** [comment]
Just need translated `name` and `about` for the remaining ones, you can just comment these here and I can copy paste them into separate files.
`Reproducing` steps is different between the Combat one and the Visual ones, one example should be enough, I can copy paste them in the others.

**Comment by Ryuuen** [comment]
The translation for name and both tag.

name | name in Japaese | about
-- | -- | -- 
[EN] Combat bug | [JP] 戦闘仕様のバグ | ダメージなどに影響する戦闘中のバグ
[EN] Visual bug - Android | [JP] Android版の表示バグ | Android版における画面・動画表示のバグ
[EN] Visual bug - both | [JP] 両環境の表示バグ | HTML5版とAndroid版両環境における画面・動画表示のバグ
[EN] Visual bug - HTML5 | [JP] HTML5版の表示バグ | HTML5版における画面・動画表示のバグ

Replacing translation for Visual ones:
バグを再現するために、必要な手順を説明してください：（存在しない場合は削除しても良い）
1.  '...'に移動する
2. '....'にクリックする
3. バグの再現

I am sorry for my unfamiliar with GitHub editting.

**Comment by Tibowl** [comment]
Thanks! 

I've created the other templates as well. They should be visible from [here](https://github.com/Tibowl/KCBugTracker/issues/new/choose) now.

**Pull request merged**
